version: '3.8'

services:
  http-repo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-repository
    ports:
      - "80:80"
    volumes:
      - ./dist:/var/www/repo/onec
      - ./distr:/tmp/distr:ro
    command: /usr/local/bin/start-http.sh
    restart: unless-stopped
    networks:
      - repo-network

networks:
  repo-network:
    driver: bridge
