services:
  http-repo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-repository
    ports:
      - "80:80"
    volumes:
      - ./dist/pool:/var/www/repo/onec/pool
      - ./dist/dists:/var/www/repo/onec/dists
      - ./dist/db:/var/www/repo/onec/db
      - ./distr:/tmp/distr:ro
    command: /usr/local/bin/start-http.sh
    restart: unless-stopped
    networks:
      - repo-network

networks:
  repo-network:
    driver: bridge
